# Generated by Django 2.2 on 2022-02-21 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0002_auto_20220221_1452'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
    ]
