# Generated by Django 2.2 on 2022-02-23 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0007_auto_20220223_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='surname',
        ),
    ]
