# Generated by Django 2.2 on 2022-02-27 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0009_auto_20220223_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(blank=True, upload_to='photos/'),
        ),
    ]
