# Generated by Django 2.2 on 2022-02-28 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0011_auto_20220227_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='name_user',
            field=models.CharField(max_length=100, verbose_name='First Name and Last Name'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.CharField(max_length=1000, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.CharField(default='', max_length=1000, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.IntegerField(blank=True, verbose_name='Phone number'),
        ),
    ]
