# Generated by Django 2.2 on 2022-03-09 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=50, verbose_name='Имя')),
                ('surname', models.CharField(blank=True, default='', max_length=50, verbose_name='Фамилия')),
                ('date_of_birth', models.DateTimeField(verbose_name='Дата рождения')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100, verbose_name='Название')),
                ('isbn', models.IntegerField(blank=True, default=0, verbose_name='Международный Стандартный Книжный Номер')),
                ('year_of_issue', models.DateTimeField(verbose_name='Дата выпуска')),
                ('pages_count', models.IntegerField(blank=True, default=0, verbose_name='Количество страниц')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='app_library.Author', verbose_name='Магазин')),
            ],
        ),
    ]
