# Generated by Django 2.2 on 2022-03-10 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_library', '0002_remove_book_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='date_of_birth',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='book',
            name='year_of_issue',
            field=models.DateField(verbose_name='Дата выпуска'),
        ),
    ]
