# Generated by Django 2.2 on 2022-03-10 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_library', '0003_auto_20220310_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='app_library.Author', verbose_name='Автор'),
            preserve_default=False,
        ),
    ]
