# Generated by Django 2.2 on 2022-02-14 15:37

import app_news.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=36)),
                ('phone', models.IntegerField(blank=True, verbose_name='номер телефона')),
                ('is_verified', models.BooleanField(default=False)),
                ('news_count', models.IntegerField(default=0, verbose_name='количество опубликованных новостей')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name='Название')),
                ('description', models.CharField(default='', max_length=1000, verbose_name='Содержание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_ad', models.DateTimeField(auto_now=True)),
                ('views_count', models.IntegerField(default=0, verbose_name='Количество просмотров')),
                ('is_active', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=models.SET(app_news.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_user', models.CharField(max_length=100, verbose_name='Имя и фамилия')),
                ('text', models.CharField(max_length=1000, verbose_name='Текст')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app_news.News')),
                ('user', models.ForeignKey(on_delete=models.SET(app_news.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
