# Generated by Django 2.2 on 2022-02-15 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='tag',
            field=models.CharField(blank=True, max_length=100, verbose_name='Введите тег'),
        ),
    ]
