# Generated by Django 2.2 on 2022-02-17 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0003_auto_20220217_1304'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'permissions': (('publish', 'Может публиковать'),)},
        ),
    ]
