# Generated by Django 2.2 on 2022-02-17 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0004_auto_20220217_1417'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'permissions': (('publish_news', 'Может публиковать'),)},
        ),
    ]
