# Generated by Django 2.2 on 2022-02-17 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0005_auto_20220217_1420'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': (('verify_profile', 'Может верифицировать'),)},
        ),
    ]
