# Generated by Django 2.2 on 2022-03-03 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='', max_length=100, verbose_name='Название')),
                ('description', models.CharField(default='', max_length=1000, verbose_name='Описание магазина')),
            ],
            options={
                'verbose_name': 'магазин',
                'verbose_name_plural': 'магазины',
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100, verbose_name='Название')),
                ('description', models.CharField(default='', max_length=1000, verbose_name='Описание акции')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='app_shop.Shop', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'акция',
                'verbose_name_plural': 'акции',
            },
        ),
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(blank=True, verbose_name='Баланс')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'персональная информация',
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100, verbose_name='Название')),
                ('price', models.IntegerField(blank=True, verbose_name='Баланс')),
                ('description', models.CharField(default='', max_length=1000, verbose_name='Описание товара')),
                ('buyer', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to=settings.AUTH_USER_MODEL, verbose_name='Покупатель')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='app_shop.Shop', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'предложение',
                'verbose_name_plural': 'предложения',
            },
        ),
    ]
