# Generated by Django 2.2 on 2022-03-03 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='balance',
            field=models.IntegerField(blank=True, default=0, verbose_name='Баланс'),
        ),
    ]
