# Generated by Django 2.2 on 2022-03-03 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0004_auto_20220303_2132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='buyer',
        ),
        migrations.AddField(
            model_name='offer',
            name='buyer_id',
            field=models.IntegerField(blank=True, default=0, verbose_name='ID покупателя'),
            preserve_default=False,
        ),
    ]
