# Generated by Django 4.0.3 on 2022-03-15 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personalinfo',
            options={'verbose_name': 'персональная информация', 'verbose_name_plural': 'персональная информация'},
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='status',
            field=models.IntegerField(blank=True, default=0, verbose_name='Сумма покупок'),
        ),
    ]
