# Generated by Django 4.0.3 on 2022-03-15 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_users', '0002_alter_personalinfo_options_personalinfo_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_bought',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='buyer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL, verbose_name='Покупатель'),
        ),
    ]
