# Generated by Django 4.0.3 on 2022-03-15 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0003_product_is_bought_alter_product_buyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='in_basket',
            field=models.BooleanField(default=False),
        ),
    ]
