# Generated by Django 4.0.3 on 2022-03-15 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0004_product_in_basket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='in_basket',
            field=models.BooleanField(default=False, verbose_name='В корзине'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_bought',
            field=models.BooleanField(default=False, verbose_name='Куплено'),
        ),
        migrations.AlterField(
            model_name='product',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='app_users.shop', verbose_name='Магазин'),
        ),
    ]
