# Generated by Django 4.0.3 on 2022-03-15 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0005_alter_product_in_basket_alter_product_is_bought_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='count_buy',
            field=models.IntegerField(default=0, verbose_name='Количество покупок'),
        ),
        migrations.AddField(
            model_name='product',
            name='count_product',
            field=models.IntegerField(default=1, verbose_name='Количество товара'),
        ),
    ]
