# Generated by Django 4.0.3 on 2022-03-15 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0008_remove_product_buyer_remove_product_in_basket_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerproduct',
            name='product',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='buyer_products', to='app_users.product', verbose_name='Товар'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='buyerproduct',
            name='in_basket',
            field=models.BooleanField(default=True, verbose_name='В корзине'),
        ),
    ]
