# Generated by Django 4.0.3 on 2022-03-15 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0009_buyerproduct_product_alter_buyerproduct_in_basket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyerproduct',
            name='in_basket',
        ),
    ]
